# Generated by Django 4.2.1 on 2023-05-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="img",
            field=models.ImageField(blank=True, default=None, upload_to="images/"),
        ),
    ]
