# Generated by Django 4.2.1 on 2023-05-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
